# Generated by Django 2.0.6 on 2018-06-23 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30, null=True)),
                ('classification', models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year'), ('third', 'Third Year'), ('fourth', 'Fourth Year'), ('fifth+', 'Fifth Year or higher'), ('grad', 'Graduate Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='first', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
