# Generated by Django 2.0.6 on 2018-07-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_current_match_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
