# Generated by Django 2.0.6 on 2018-07-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180704_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_match_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
